alias bashp='vi ~/.bash_profile'
alias sshcse='ssh pete9934@kh4250-07.cselabs.umn.edu'
alias tolabs='scp -r ~/spring2018/4061/rec6 pete9934@kh4250-07.cselabs.umn.edu:~/Documents/4061/'
alias fromlabs='scp -r pete9934@kh4250-07.cselabs.umn.edu:~/Documents/4061/rec6 ~/spring2018/4061'
alias bashrc='vi ~/.bashrc'
alias pingport='nc -vz' # argument order: <endpoint> <port>
alias gcm='git commit -m'
alias pete='cd ~/csci2041/repo-pete9934'
alias rvm-restart='rvm_reload_flag=1 source '\''/Users/brianpeterson/.rvm/scripts/rvm'\'''
alias srcbash='source ~/.bash_profile'
alias tmux='tmuxinator default'
alias vi='vim'
alias vimrc='vi ~/.vimrc'
alias gs='git status'
alias gck='git checkout'
alias gb='git branch'
alias tmux='tmuxinator default'
alias tmuxconf='vi ~/.tmux.conf'
alias la='ls -A'
alias ll='ls -l'
alias pdd='cd ~/github/csci3081/'
alias cpplintcheck='~/.cpplint.py --repository=. src/*.cc src/*.h'
